### ISSUE TITLE
Fix Printing on Fax Machine

### ISSUE THREAD

**Issue by klwadland** [marderlab/computers#29]
The Fax machine is printing nearly blank pages. I've already replaced the toner cartridge with a fresh one and the device still thinks the toner is low and isn't printing pages normally.

**Comment by cosmojg** [comment]
I'll take a look!

**Comment by klwadland** [comment]
Can you determine if this is an easy/simple fix? If so, it can be fixed as a lower priority item. If not, we can close this ticket and Eve said I can order a new fax machine for the lab.

**Comment by cosmojg** [comment]
I took a look, and it's not worth fixing. Let's buy a new one!
