### ISSUE TITLE
Microscope Software for Mara's rig computer

### ISSUE THREAD

**Issue by klwadland** [marderlab/computers#37]
Mara's new rig computer (Karkinos) needs the appropriate Leica software so she can use the camera on her microscope. The correct software is on her old rig computer (Neuronaut--on Janis's old desk) for reference. Mara has tried to move the software over to her new rig computer and was unsuccessful. The software won't open and find the microscope camera properly. You should try finding the software on Leica's website/online, first or if you can get it to transfer from Neuronaut and work properly that would also be fantastic. If we can't get the software to run properly on our own we may need to call Leica's service dept. down the line.

**Comment by cosmojg** [comment]
On it!

**Comment by cosmojg** [comment]
Note to self: need to ask Mara about how she connected previously.

**Comment by cosmojg** [comment]
> Note to self: need to ask Mara about how she connected previously.

Apparently she used built-in FireWire ports on the previous tower. I'm going to try and transplant these to the new tower on Friday when she isn't using the rig.

**Comment by cosmojg** [comment]
I've yet to attempt the above solution, and I'm still waiting on a response from Leica. I sent them a follow-up email. I need to talk to Mara again and see what I can do.

**Comment by cosmojg** [comment]
We've successfully transplanted the FireWire 3-Port PCI card, but we're still struggling to get the microscope working. I'll keep you updated.

**Comment by cosmojg** [comment]
@klwadland @Liaro0903 I finally managed to get someone from Leica on the phone whose directly involved with the cameras! He confirmed that other users of this camera have got it working fine with Windows 10, and he thinks the issue might be with the FireWire card. He says they've had trouble with the manufacturer of the card we're using in the past (SIIG). Before buying a several-thousand-dollar USB camera to replace the one we already have, he suggested that we test a couple different ~$30 FireWire B cards. I think this one looks like a good bet: https://www.amazon.com/YOTOCAP-Firewire-Controller-Adapter-Server/dp/B08JTGSDMX/ref=sr_1_4?keywords=firewire+b+card&qsid=137-5807818-2802060&sr=8-4&sres=B092VCDPSV%2CB08JTGSDMX%2CB092QSG29S%2CB08D3PBXF3%2CB07QPDN3XK%2CB06XXTSF8K%2CB07Q2G79QG%2CB004QY7M3Y%2CB07GJNMLYM%2CB07N2WQZTS%2CB083W2XJBM%2CB01CN1F1ZM%2CB01ARAH6O0%2CB09CYJGVGR%2CB08SMNGYRT%2CB081VHSB2V

That one can be hooked up to the internal power supply which he recommends doing since the card powers the camera.

**Comment by klwadland** [comment]
I've submitted the order for the FireWire card. Hopefully, it'll be here at the beginning of next week.

**Comment by klwadland** [comment]
The new FireWire card has arrived and is sitting on the cart by my desk. It's in a small box.

**Comment by Liaro0903** [comment]
Some updates on the new firewire card. The card works with external storage, but still nothing from the DFC camera. I tried it with the Leica driver, Texas instrument driver, and the legacy driver. Device manager and LAS still don't show anything. I tested these with internal power supply hooked up, but assuming I hooked it up correctly.
On the LAS installation file, there was an analyze pc performance function. After running it, it says "Leica1394bus OHCI TI (the Leica driver) is not verified for use with Leica DFC cameras", and it says the same thing for all three different drivers. I am still not sure if it is a driver issue (not working with the operating system) or a card issue.

**Comment by klwadland** [comment]
I wonder if Leica would know if a particular driver works better than others with their equipment and the OS? As Cosmo passed along, they did say that people have been able to get their cameras working with Windows 10 computers before.

**Comment by klwadland** [comment]
@Liaro0903 Could you please put Mara's rig computer back into one piece so she can use it for experiments while you're not trying to sort out the camera issue? I tried to reassemble it myself, but I wasn't sure where the hard drive went.

**Comment by Liaro0903** [comment]
So updates from today:
1. Called Leica again, the customer support guy agreed to try to test on another computer, and if it still doesn't work, it's probably the camera issue.
2. Hooked up another firewire camera (DFC360 FX) to Karkinos, and the camera is finally being detected! So conclusion for the camera in Mara's rig is that it is probably dead. This also explains why when I hooked it up to another windows 7 machine, it is also not being detected.

**Comment by klwadland** [comment]
Could you please swap the working firewire camera to Mara's rig so she has a functioning camera when she does experiments? Then we can deal with replacing the busted one in our own time. No one is using the rig the working camera is currently on so they won't be hindered by the lack of a camera on the microscope.

**Comment by Liaro0903** [comment]
Yup, just did! Tested and it's working.

**Comment by Mayapalmer** [comment]
In regards to whether this camera should be used on the other rig: Representative (Scott) said that we could try troubleshooting again or if we are certain that it is broken, it might make more sense to just buy a new camera. Servicing the 365 if possible would be half to two thirds as expensive as buying a new, better camera. He recommended upgrading to the K3M or the K5.

**Comment by klwadland** [comment]
The new microscope camera has arrived and was successfully installed (software too) by Maya last week.
