### ISSUE TITLE
Set up Crabsort for Leora

### ISSUE THREAD

**Issue by klwadland** [marderlab/computers#41]
Leora needs access to a computer with Crabsort. This can be either Neuronaut or if you can get Crabsort to install on the communal Mac in the back (near the printer) that would also be great. I can't get Matlab to install or run on this computer because it won't recognize that I have access to the license.

**Comment by cosmojg** [comment]
On it! I'll figure something out within the next couple of days.

**Comment by cosmojg** [comment]
Neuronaut is probably too slow for Crabsort. I'll try and get it working on the communal Mac, but if that doesn't work, I think I'll set her up on either Gilgamesh or Neuromancer instead.

**Comment by cosmojg** [comment]
I've successfully installed MATLAB and Crabsort on the Public account on the communal Mac.

**Comment by cosmojg** [comment]
@klwadland I have also set up an account for Leora on Neuromancer complete with MATLAB and Crabsort. (Her password is the same as Emma's.)

**Comment by cosmojg** [comment]
@klwadland I have also set up an account for Leora on Neuromancer complete with MATLAB and Crabsort.
