### ISSUE TITLE
Connect Poliwag computer to the internet

### ISSUE THREAD

**Issue by klwadland** [marderlab/computers#44]
The computer for the rotation/undergrad rig isn't connecting to the internet despite being physically connected via an ethernet cable to the modem.

**Comment by klwadland** [comment]
The other computer in the same rig room is connected via the same modem and connected to the network. So the issue is probably with a bad ethernet cable for Poliwag's computer.

**Comment by Liaro0903** [comment]
I replugged the ethernet cable and it's working now!
