### ISSUE TITLE
File share permissions

### ISSUE THREAD

**Issue by emmalcarlson** [marderlab/computers#45]
Unable to add to fileshare. 
![IMG-6833](https://user-images.githubusercontent.com/97979157/149993608-aa50382a-0dc4-4c34-9e83-7d2a06400f1f.jpg)

My email is emmacarlson@brandeis.edu if we need to coordinate a time to meet.

**Comment by klwadland** [comment]
We tried logging in with my info too and were still denied. I wonder if the issue is with the computer and not the fileshare? Emma was able to log in on her personal laptop and then do a multi-step transfer to the fileshare, but that's not ideal long-term.

**Comment by Liaro0903** [comment]
I'm coordinating with emma to find a time to meet.
